"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.adminRouter = void 0;
const express_1 = require("express");
const admin_controller_1 = require("../controllers/admin.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const rbac_middleware_1 = require("../middlewares/rbac.middleware");
exports.adminRouter = (0, express_1.Router)();
exports.adminRouter.use(auth_middleware_1.authenticate, (0, rbac_middleware_1.requireRoles)('super_admin'));
exports.adminRouter.get('/users', admin_controller_1.adminController.users);
exports.adminRouter.get('/organizations', admin_controller_1.adminController.organizations);
exports.adminRouter.get('/subscriptions', admin_controller_1.adminController.subscriptions);
exports.adminRouter.get('/audit-logs', admin_controller_1.adminController.auditLogs);
exports.adminRouter.get('/stats', admin_controller_1.adminController.stats);
