"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.authRouter = void 0;
const express_1 = require("express");
const auth_controller_1 = require("../controllers/auth.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const rate_limit_middleware_1 = require("../middlewares/rate-limit.middleware");
const validate_middleware_1 = require("../middlewares/validate.middleware");
const auth_validation_1 = require("../validations/auth.validation");
exports.authRouter = (0, express_1.Router)();
exports.authRouter.post('/register', rate_limit_middleware_1.authLimiter, (0, validate_middleware_1.validate)(auth_validation_1.registerSchema), auth_controller_1.authController.register);
exports.authRouter.post('/login', rate_limit_middleware_1.authLimiter, (0, validate_middleware_1.validate)(auth_validation_1.loginSchema), auth_controller_1.authController.login);
exports.authRouter.post('/google', rate_limit_middleware_1.authLimiter, (0, validate_middleware_1.validate)(auth_validation_1.googleSchema), auth_controller_1.authController.google);
exports.authRouter.post('/refresh-token', (0, validate_middleware_1.validate)(auth_validation_1.refreshTokenSchema), auth_controller_1.authController.refreshToken);
exports.authRouter.post('/logout', auth_middleware_1.authenticate, auth_controller_1.authController.logout);
exports.authRouter.get('/me', auth_middleware_1.authenticate, auth_controller_1.authController.me);
exports.authRouter.patch('/me', auth_middleware_1.authenticate, auth_controller_1.authController.updateMe);
exports.authRouter.post('/change-password', auth_middleware_1.authenticate, auth_controller_1.authController.changePassword);
exports.authRouter.post('/forgot-password', rate_limit_middleware_1.authLimiter, (0, validate_middleware_1.validate)(auth_validation_1.forgotPasswordSchema), auth_controller_1.authController.forgotPassword);
exports.authRouter.post('/reset-password', rate_limit_middleware_1.authLimiter, (0, validate_middleware_1.validate)(auth_validation_1.resetPasswordSchema), auth_controller_1.authController.resetPassword);
exports.authRouter.post('/accept-invite', rate_limit_middleware_1.authLimiter, (0, validate_middleware_1.validate)(auth_validation_1.acceptInviteSchema), auth_controller_1.authController.acceptInvite);
