"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.customerRouter = exports.leadRouter = void 0;
const express_1 = require("express");
const crm_controller_1 = require("../controllers/crm.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const rbac_middleware_1 = require("../middlewares/rbac.middleware");
const tenant_middleware_1 = require("../middlewares/tenant.middleware");
const validate_middleware_1 = require("../middlewares/validate.middleware");
const crm_validation_1 = require("../validations/crm.validation");
exports.leadRouter = (0, express_1.Router)();
exports.customerRouter = (0, express_1.Router)();
exports.leadRouter.use(auth_middleware_1.authenticate, tenant_middleware_1.requireTenant);
exports.leadRouter.post('/', (0, rbac_middleware_1.requireMinRole)('manager'), (0, validate_middleware_1.validate)(crm_validation_1.createLeadSchema), crm_controller_1.crmController.createLead);
exports.leadRouter.get('/', (0, validate_middleware_1.validate)(crm_validation_1.listLeadSchema), crm_controller_1.crmController.listLeads);
exports.leadRouter.get('/:id', (0, validate_middleware_1.validate)(crm_validation_1.idSchema), crm_controller_1.crmController.getLead);
exports.leadRouter.patch('/:id', (0, rbac_middleware_1.requireMinRole)('manager'), (0, validate_middleware_1.validate)(crm_validation_1.updateLeadSchema), crm_controller_1.crmController.updateLead);
exports.leadRouter.delete('/:id', (0, rbac_middleware_1.requireMinRole)('admin'), (0, validate_middleware_1.validate)(crm_validation_1.idSchema), crm_controller_1.crmController.deleteLead);
exports.customerRouter.use(auth_middleware_1.authenticate, tenant_middleware_1.requireTenant, (0, rbac_middleware_1.requireMinRole)('admin'));
exports.customerRouter.post('/', (0, rbac_middleware_1.requireMinRole)('manager'), (0, validate_middleware_1.validate)(crm_validation_1.createCustomerSchema), crm_controller_1.crmController.createCustomer);
exports.customerRouter.get('/', (0, validate_middleware_1.validate)(crm_validation_1.listCustomerSchema), crm_controller_1.crmController.listCustomers);
exports.customerRouter.patch('/:id', (0, rbac_middleware_1.requireMinRole)('admin'), (0, validate_middleware_1.validate)(crm_validation_1.updateCustomerSchema), crm_controller_1.crmController.updateCustomer);
exports.customerRouter.delete('/:id', (0, rbac_middleware_1.requireMinRole)('admin'), (0, validate_middleware_1.validate)(crm_validation_1.idSchema), crm_controller_1.crmController.deleteCustomer);
