"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.apiRouter = void 0;
const express_1 = require("express");
const admin_routes_1 = require("./admin.routes");
const ai_routes_1 = require("./ai.routes");
const ai_usage_routes_1 = require("./ai-usage.routes");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const tenant_middleware_1 = require("../middlewares/tenant.middleware");
const subscription_middleware_1 = require("../middlewares/subscription.middleware");
const analytics_routes_1 = require("./analytics.routes");
const auth_routes_1 = require("./auth.routes");
const billing_routes_1 = require("./billing.routes");
const crm_routes_1 = require("./crm.routes");
const notification_routes_1 = require("./notification.routes");
const organization_routes_1 = require("./organization.routes");
const project_routes_1 = require("./project.routes");
exports.apiRouter = (0, express_1.Router)();
const activeWorkspace = [auth_middleware_1.authenticate, tenant_middleware_1.requireTenant, subscription_middleware_1.requireActiveSubscription];
exports.apiRouter.use('/auth', auth_routes_1.authRouter);
exports.apiRouter.use('/organizations', organization_routes_1.organizationRouter);
exports.apiRouter.use('/leads', ...activeWorkspace, crm_routes_1.leadRouter);
exports.apiRouter.use('/customers', ...activeWorkspace, crm_routes_1.customerRouter);
exports.apiRouter.use('/projects', ...activeWorkspace, project_routes_1.projectRouter);
exports.apiRouter.use('/tasks', ...activeWorkspace, project_routes_1.taskRouter);
exports.apiRouter.use('/ai', ai_usage_routes_1.aiUsageRouter, ai_routes_1.aiRouter);
exports.apiRouter.use('/analytics', ...activeWorkspace, analytics_routes_1.analyticsRouter);
exports.apiRouter.use('/billing', billing_routes_1.billingRouter);
exports.apiRouter.use('/notifications', ...activeWorkspace, notification_routes_1.notificationRouter);
exports.apiRouter.use('/admin', admin_routes_1.adminRouter);
