"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.organizationRouter = void 0;
const express_1 = require("express");
const organization_controller_1 = require("../controllers/organization.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const rbac_middleware_1 = require("../middlewares/rbac.middleware");
const tenant_middleware_1 = require("../middlewares/tenant.middleware");
const subscription_middleware_1 = require("../middlewares/subscription.middleware");
const validate_middleware_1 = require("../middlewares/validate.middleware");
const organization_validation_1 = require("../validations/organization.validation");
exports.organizationRouter = (0, express_1.Router)();
exports.organizationRouter.use(auth_middleware_1.authenticate);
exports.organizationRouter.use(subscription_middleware_1.requireActiveOrganizationRoute);
exports.organizationRouter.post('/', (0, validate_middleware_1.validate)(organization_validation_1.createOrganizationSchema), organization_controller_1.organizationController.create);
exports.organizationRouter.get('/current', tenant_middleware_1.requireTenant, organization_controller_1.organizationController.current);
exports.organizationRouter.get('/current/members', tenant_middleware_1.requireTenant, organization_controller_1.organizationController.members);
exports.organizationRouter.post('/current/members', tenant_middleware_1.requireTenant, (0, rbac_middleware_1.requireMinRole)('manager'), (0, validate_middleware_1.validate)(organization_validation_1.inviteMemberSchema), organization_controller_1.organizationController.inviteMember);
exports.organizationRouter.patch('/current/members/:memberId', tenant_middleware_1.requireTenant, (0, rbac_middleware_1.requireMinRole)('admin'), (0, validate_middleware_1.validate)(organization_validation_1.updateMemberSchema), organization_controller_1.organizationController.updateMember);
exports.organizationRouter.delete('/current/members/:memberId', tenant_middleware_1.requireTenant, (0, rbac_middleware_1.requireMinRole)('admin'), (0, validate_middleware_1.validate)(organization_validation_1.memberActionSchema), organization_controller_1.organizationController.removeMember);
exports.organizationRouter.patch('/:id', tenant_middleware_1.requireTenant, (0, rbac_middleware_1.requireMinRole)('admin'), (0, validate_middleware_1.validate)(organization_validation_1.updateOrganizationSchema), organization_controller_1.organizationController.update);
