"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.platformRouter = void 0;
const { Router } = require("express");
const rateLimit = require("express-rate-limit").default || require("express-rate-limit");
const { platformController: c } = require("../controllers/platform.controller");
const { requirePlatformSuperAdmin } = require("../middlewares/platform-auth.middleware");
const { validate } = require("../middlewares/validate.middleware");
const { platformValidation: v } = require("../validations/platform.validation");
exports.platformRouter = Router();
const platformLoginLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 8, standardHeaders: true, legacyHeaders: false });
exports.platformRouter.post('/auth/register', platformLoginLimiter, validate(v.register), c.register);
exports.platformRouter.post('/auth/login', platformLoginLimiter, validate(v.login), c.login);
exports.platformRouter.post('/auth/refresh', platformLoginLimiter, validate(v.refresh), c.refresh);
exports.platformRouter.use(requirePlatformSuperAdmin);
exports.platformRouter.get('/auth/me', c.me);
exports.platformRouter.post('/auth/logout', c.logout);
exports.platformRouter.get('/overview', c.overview);
exports.platformRouter.get('/organizations', validate(v.list), c.organizations);
exports.platformRouter.get('/organizations/:id', validate(v.id), c.organization);
exports.platformRouter.patch('/organizations/:id/status', validate(v.organizationStatus), c.organizationStatus);
exports.platformRouter.delete('/organizations/:id', validate(v.id), c.deleteOrganization);
exports.platformRouter.get('/users', validate(v.list), c.users);
exports.platformRouter.get('/plans', validate(v.list), c.plans);
exports.platformRouter.post('/plans', validate(v.plan), c.createPlan);
exports.platformRouter.patch('/plans/:id', validate(v.planUpdate), c.updatePlan);
exports.platformRouter.delete('/plans/:id', validate(v.id), c.deletePlan);
exports.platformRouter.get('/subscriptions', validate(v.list), c.subscriptions);
exports.platformRouter.patch('/subscriptions/:id/action', validate(v.subscriptionAction), c.subscriptionAction);
exports.platformRouter.get('/payments', validate(v.list), c.payments);
exports.platformRouter.patch('/payments/:id/decision', validate(v.paymentDecision), c.paymentDecision);
exports.platformRouter.get('/invoices', validate(v.list), c.invoices);
exports.platformRouter.patch('/invoices/:id/status', validate(v.invoiceStatus), c.invoiceStatus);
exports.platformRouter.get('/activity-logs', validate(v.list), c.activities);
exports.platformRouter.get('/reports', c.reports);
exports.platformRouter.get('/settings', c.settings);
exports.platformRouter.put('/settings', validate(v.setting), c.setSetting);
