"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.taskRouter = exports.projectRouter = void 0;
const express_1 = require("express");
const project_controller_1 = require("../controllers/project.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const rbac_middleware_1 = require("../middlewares/rbac.middleware");
const tenant_middleware_1 = require("../middlewares/tenant.middleware");
const validate_middleware_1 = require("../middlewares/validate.middleware");
const crm_validation_1 = require("../validations/crm.validation");
const project_validation_1 = require("../validations/project.validation");
exports.projectRouter = (0, express_1.Router)();
exports.taskRouter = (0, express_1.Router)();
exports.projectRouter.use(auth_middleware_1.authenticate, tenant_middleware_1.requireTenant);
exports.projectRouter.post('/', (0, rbac_middleware_1.requireMinRole)('manager'), (0, validate_middleware_1.validate)(project_validation_1.createProjectSchema), project_controller_1.projectController.createProject);
exports.projectRouter.get('/', (0, validate_middleware_1.validate)(project_validation_1.listProjectSchema), project_controller_1.projectController.listProjects);
exports.projectRouter.get('/:id/members', (0, rbac_middleware_1.requireMinRole)('manager'), (0, validate_middleware_1.validate)(crm_validation_1.idSchema), project_controller_1.projectController.assignments);
exports.projectRouter.post('/:id/invitations', (0, rbac_middleware_1.requireMinRole)('manager'), (0, validate_middleware_1.validate)(project_validation_1.inviteProjectMemberSchema), project_controller_1.projectController.inviteMember);
exports.projectRouter.patch('/:id/invitations/:invitationId/respond', (0, validate_middleware_1.validate)(project_validation_1.respondInvitationSchema), project_controller_1.projectController.respondInvitation);
exports.projectRouter.delete('/:id/members/:userId', (0, rbac_middleware_1.requireMinRole)('manager'), (0, validate_middleware_1.validate)(project_validation_1.projectMemberActionSchema), project_controller_1.projectController.revokeMember);
exports.projectRouter.get('/:id', (0, validate_middleware_1.validate)(crm_validation_1.idSchema), project_controller_1.projectController.getProject);
exports.projectRouter.get('/:id/kanban', (0, validate_middleware_1.validate)(crm_validation_1.idSchema), project_controller_1.projectController.kanban);
exports.projectRouter.patch('/:id', (0, rbac_middleware_1.requireMinRole)('manager'), (0, validate_middleware_1.validate)(project_validation_1.updateProjectSchema), project_controller_1.projectController.updateProject);
exports.projectRouter.delete('/:id', (0, rbac_middleware_1.requireMinRole)('admin'), (0, validate_middleware_1.validate)(crm_validation_1.idSchema), project_controller_1.projectController.deleteProject);
exports.taskRouter.use(auth_middleware_1.authenticate, tenant_middleware_1.requireTenant);
exports.taskRouter.post('/', (0, validate_middleware_1.validate)(project_validation_1.createTaskSchema), project_controller_1.projectController.createTask);
exports.taskRouter.get('/', (0, validate_middleware_1.validate)(project_validation_1.listTaskSchema), project_controller_1.projectController.listTasks);
exports.taskRouter.patch('/:id', (0, validate_middleware_1.validate)(project_validation_1.updateTaskSchema), project_controller_1.projectController.updateTask);
